language: java
jdk: openjdk8

services:
  - docker

install: true
script: docker build -t registry.heroku.com/ivvq-patterns/waifu-market .

deploy:
  provider: script
  script: bash docker_push
  on:
    repo: M2DL/ivvq-2020-project-patterns
    branch: heroku