version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "trust"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432

  app:
    container_name: waifu_market-desu_container
    image: waifu_market-desu
    build: ./
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=PREPROD"

  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    links:
      - app

  e2e_tests:
    container_name: e2e_tests_container
    image: e2e_tests
    build: ./e2e
    command: ./wait-for-it.sh -t 60 selenium:4444 -- ./wait-for-it.sh -t 60 app:8080 -- ./node_modules/.bin/nightwatch
    depends_on:
      - selenium
      - app
    links:
      - app