version: '3'
services:
  postgres-db:
    container_name: postgres_container
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  app:
    container_name: waifu_market-dess_container
    image: waifu_market-dess
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
