version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "trust"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432

  app:
    container_name: waifu_market-dess_container
    image: waifu_market-dess
    build: ./
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=PREPROD"

volumes:
  postgres-data: